server:
  port: 9001
spring:
  application:
    name: cloud-system # 项目名称尽量用小写
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/ # 指定注册中心地址
  instance:
    preferIpAddress: true